#!/bin/sh

sleep_random 100

removeprefix=false

for prefix in "$(legacy_prefixes)" ; do
    if [[ $prefix ]] ; then
	echo "Found not routed prefix: ${prefix}"
        uci del_list network.dhcp.ip6prefix=''${prefix}''
        removeprefix=true
    fi
done

if ! $removeprefix; then
    exit 0
fi

uci commit network

if uci show "/etc/config/network" > /dev/null ; then
    echo "Everything is Fine. Reload Network!"
    /etc/init.d/network reload
    echo "Flush Deprecated Entries!"
    sleep 5
    ip -6 address flush deprecated
fi